### ISSUE TITLE
Error raised.

### ISSUE THREAD

**Issue by qyc9533** [DeepLearnXMU/SSR#1]
when running:

bash src/scripts-ni-c012/lora/cl2/llama2-7b-chat/llama2-7b-chat.lora.cl_queue2_rp.3ep.bs32x1x1.lr2e-04.bf16.sh

I have changed parameters "REPO_ROOT_DIR" and "MODEL_DIR".

An error raised:
AssertionError: Provided path (/media/guest_opt/qyc/SSR-main/saves/ni-c012/LLAMA2-7B-Chat/lora/trans/bs32x1x1-3ep-bf16) does not contain a LoRA weight.

It seems that the first dataset "trans" is not trained.

what's wrong with that and what should I do ?

**Comment by Xxxxxsun** [comment]
Hi, I encountered the very same problem. Have you solved it yet?

**Comment by unsioer** [comment]
Hello, in Stage 1 of the continual learning based on SSR, we fine-tune the LLM on a single task without any additional operations. Therefore, as for the example, you should first train the "trans" task to obtain the checkpoint.
